#############################################################################
# Makefile for building: terminal.app/Contents/MacOS/terminal
# Generated by qmake (3.1) (Qt 5.10.0)
# Project:  ../terminal/terminal.pro
# Template: app
# Command: /Users/austin/Qt/5.10.0/clang_64/bin/qmake -o Makefile ../terminal/terminal.pro -spec macx-clang CONFIG+=x86_64
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I../terminal -I. -I../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers -I../../../../5.10.0/clang_64/lib/QtGui.framework/Headers -I../../../../5.10.0/clang_64/lib/QtSerialPort.framework/Headers -I../../../../5.10.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../../5.10.0/clang_64/mkspecs/macx-clang -F/Users/austin/Qt/5.10.0/clang_64/lib
QMAKE         = /Users/austin/Qt/5.10.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/austin/Qt/5.10.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/austin/Qt/5.10.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = terminal1.0.0
DISTDIR = /Users/austin/Qt/Examples/Qt-5.10.0/serialport/test/.tmp/terminal1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/austin/Qt/5.10.0/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/austin/Qt/5.10.0/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtSerialPort -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../terminal/main.cpp \
		../terminal/mainwindow.cpp \
		../terminal/settingsdialog.cpp \
		../terminal/console.cpp qrc_terminal.cpp \
		moc_mainwindow.cpp \
		moc_settingsdialog.cpp \
		moc_console.cpp
OBJECTS       = main.o \
		mainwindow.o \
		settingsdialog.o \
		console.o \
		qrc_terminal.o \
		moc_mainwindow.o \
		moc_settingsdialog.o \
		moc_console.o
DIST          = ../../../../5.10.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../../5.10.0/clang_64/mkspecs/qdevice.pri \
		../../../../5.10.0/clang_64/mkspecs/features/device_config.prf \
		../../../../5.10.0/clang_64/mkspecs/common/unix.conf \
		../../../../5.10.0/clang_64/mkspecs/common/mac.conf \
		../../../../5.10.0/clang_64/mkspecs/common/macx.conf \
		../../../../5.10.0/clang_64/mkspecs/common/sanitize.conf \
		../../../../5.10.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../../5.10.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../5.10.0/clang_64/mkspecs/common/clang.conf \
		../../../../5.10.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../../5.10.0/clang_64/mkspecs/qconfig.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../5.10.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../../5.10.0/clang_64/mkspecs/features/qt_config.prf \
		../../../../5.10.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../5.10.0/clang_64/mkspecs/features/spec_post.prf \
		../../../../5.10.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../5.10.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../5.10.0/clang_64/mkspecs/features/toolchain.prf \
		../../../../5.10.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../5.10.0/clang_64/mkspecs/features/default_pre.prf \
		../../../../5.10.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../5.10.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../../5.10.0/clang_64/mkspecs/features/default_post.prf \
		../../../../5.10.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../5.10.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../5.10.0/clang_64/mkspecs/features/mac/mac.prf \
		../../../../5.10.0/clang_64/mkspecs/features/warn_on.prf \
		../../../../5.10.0/clang_64/mkspecs/features/qt.prf \
		../../../../5.10.0/clang_64/mkspecs/features/resources.prf \
		../../../../5.10.0/clang_64/mkspecs/features/moc.prf \
		../../../../5.10.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../5.10.0/clang_64/mkspecs/features/uic.prf \
		../../../../5.10.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../../5.10.0/clang_64/mkspecs/features/qmake_use.prf \
		../../../../5.10.0/clang_64/mkspecs/features/file_copies.prf \
		../../../../5.10.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../../5.10.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../5.10.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../5.10.0/clang_64/mkspecs/features/exceptions.prf \
		../../../../5.10.0/clang_64/mkspecs/features/yacc.prf \
		../../../../5.10.0/clang_64/mkspecs/features/lex.prf \
		../terminal/terminal.pro ../terminal/mainwindow.h \
		../terminal/settingsdialog.h \
		../terminal/console.h ../terminal/main.cpp \
		../terminal/mainwindow.cpp \
		../terminal/settingsdialog.cpp \
		../terminal/console.cpp
QMAKE_TARGET  = terminal
DESTDIR       = 
TARGET        = terminal.app/Contents/MacOS/terminal

####### Custom Variables
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_settingsdialog.h $(OBJECTS)  
	@test -d terminal.app/Contents/MacOS/ || mkdir -p terminal.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../terminal/terminal.pro ../../../../5.10.0/clang_64/mkspecs/macx-clang/qmake.conf ../../../../5.10.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../../5.10.0/clang_64/mkspecs/qdevice.pri \
		../../../../5.10.0/clang_64/mkspecs/features/device_config.prf \
		../../../../5.10.0/clang_64/mkspecs/common/unix.conf \
		../../../../5.10.0/clang_64/mkspecs/common/mac.conf \
		../../../../5.10.0/clang_64/mkspecs/common/macx.conf \
		../../../../5.10.0/clang_64/mkspecs/common/sanitize.conf \
		../../../../5.10.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../../5.10.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../5.10.0/clang_64/mkspecs/common/clang.conf \
		../../../../5.10.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../../5.10.0/clang_64/mkspecs/qconfig.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../5.10.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../../5.10.0/clang_64/mkspecs/features/qt_config.prf \
		../../../../5.10.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../5.10.0/clang_64/mkspecs/features/spec_post.prf \
		../../../../5.10.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../5.10.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../5.10.0/clang_64/mkspecs/features/toolchain.prf \
		../../../../5.10.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../5.10.0/clang_64/mkspecs/features/default_pre.prf \
		../../../../5.10.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../5.10.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../../5.10.0/clang_64/mkspecs/features/default_post.prf \
		../../../../5.10.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../5.10.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../5.10.0/clang_64/mkspecs/features/mac/mac.prf \
		../../../../5.10.0/clang_64/mkspecs/features/warn_on.prf \
		../../../../5.10.0/clang_64/mkspecs/features/qt.prf \
		../../../../5.10.0/clang_64/mkspecs/features/resources.prf \
		../../../../5.10.0/clang_64/mkspecs/features/moc.prf \
		../../../../5.10.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../5.10.0/clang_64/mkspecs/features/uic.prf \
		../../../../5.10.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../../5.10.0/clang_64/mkspecs/features/qmake_use.prf \
		../../../../5.10.0/clang_64/mkspecs/features/file_copies.prf \
		../../../../5.10.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../../5.10.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../5.10.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../5.10.0/clang_64/mkspecs/features/exceptions.prf \
		../../../../5.10.0/clang_64/mkspecs/features/yacc.prf \
		../../../../5.10.0/clang_64/mkspecs/features/lex.prf \
		../terminal/terminal.pro \
		../terminal/terminal.qrc \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../../5.10.0/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../../5.10.0/clang_64/lib/QtSerialPort.framework/QtSerialPort.prl \
		../../../../5.10.0/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile ../terminal/terminal.pro -spec macx-clang CONFIG+=x86_64
../../../../5.10.0/clang_64/mkspecs/features/spec_pre.prf:
../../../../5.10.0/clang_64/mkspecs/qdevice.pri:
../../../../5.10.0/clang_64/mkspecs/features/device_config.prf:
../../../../5.10.0/clang_64/mkspecs/common/unix.conf:
../../../../5.10.0/clang_64/mkspecs/common/mac.conf:
../../../../5.10.0/clang_64/mkspecs/common/macx.conf:
../../../../5.10.0/clang_64/mkspecs/common/sanitize.conf:
../../../../5.10.0/clang_64/mkspecs/common/gcc-base.conf:
../../../../5.10.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../5.10.0/clang_64/mkspecs/common/clang.conf:
../../../../5.10.0/clang_64/mkspecs/common/clang-mac.conf:
../../../../5.10.0/clang_64/mkspecs/qconfig.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../5.10.0/clang_64/mkspecs/features/qt_functions.prf:
../../../../5.10.0/clang_64/mkspecs/features/qt_config.prf:
../../../../5.10.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../5.10.0/clang_64/mkspecs/features/spec_post.prf:
../../../../5.10.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../5.10.0/clang_64/mkspecs/features/mac/sdk.prf:
../../../../5.10.0/clang_64/mkspecs/features/toolchain.prf:
../../../../5.10.0/clang_64/mkspecs/features/mac/toolchain.prf:
../../../../5.10.0/clang_64/mkspecs/features/default_pre.prf:
../../../../5.10.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../5.10.0/clang_64/mkspecs/features/resolve_config.prf:
../../../../5.10.0/clang_64/mkspecs/features/default_post.prf:
../../../../5.10.0/clang_64/mkspecs/features/mac/default_post.prf:
../../../../5.10.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../5.10.0/clang_64/mkspecs/features/mac/mac.prf:
../../../../5.10.0/clang_64/mkspecs/features/warn_on.prf:
../../../../5.10.0/clang_64/mkspecs/features/qt.prf:
../../../../5.10.0/clang_64/mkspecs/features/resources.prf:
../../../../5.10.0/clang_64/mkspecs/features/moc.prf:
../../../../5.10.0/clang_64/mkspecs/features/unix/opengl.prf:
../../../../5.10.0/clang_64/mkspecs/features/uic.prf:
../../../../5.10.0/clang_64/mkspecs/features/unix/thread.prf:
../../../../5.10.0/clang_64/mkspecs/features/qmake_use.prf:
../../../../5.10.0/clang_64/mkspecs/features/file_copies.prf:
../../../../5.10.0/clang_64/mkspecs/features/mac/rez.prf:
../../../../5.10.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../../5.10.0/clang_64/mkspecs/features/testcase_targets.prf:
../../../../5.10.0/clang_64/mkspecs/features/exceptions.prf:
../../../../5.10.0/clang_64/mkspecs/features/yacc.prf:
../../../../5.10.0/clang_64/mkspecs/features/lex.prf:
../terminal/terminal.pro:
../terminal/terminal.qrc:
../../../../5.10.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../../5.10.0/clang_64/lib/QtGui.framework/QtGui.prl:
../../../../5.10.0/clang_64/lib/QtSerialPort.framework/QtSerialPort.prl:
../../../../5.10.0/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../terminal/terminal.pro -spec macx-clang CONFIG+=x86_64

qmake_all: FORCE

terminal.app/Contents/PkgInfo: 
	@test -d terminal.app/Contents || mkdir -p terminal.app/Contents
	@$(DEL_FILE) terminal.app/Contents/PkgInfo
	@echo "APPL????" > terminal.app/Contents/PkgInfo
terminal.app/Contents/Resources/empty.lproj: 
	@test -d terminal.app/Contents/Resources || mkdir -p terminal.app/Contents/Resources
	@touch terminal.app/Contents/Resources/empty.lproj
	
terminal.app/Contents/Info.plist: 
	@test -d terminal.app/Contents || mkdir -p terminal.app/Contents
	@$(DEL_FILE) terminal.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.terminal,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,terminal,g" -e "s,@LIBRARY@,terminal,g" -e "s,@TYPEINFO@,????,g" ../../../../5.10.0/clang_64/mkspecs/macx-clang/Info.plist.app >terminal.app/Contents/Info.plist

all: Makefile \
		terminal.app/Contents/PkgInfo \
		terminal.app/Contents/Resources/empty.lproj \
		terminal.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../terminal/terminal.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../5.10.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../terminal/mainwindow.h ../terminal/settingsdialog.h ../terminal/console.h $(DISTDIR)/
	$(COPY_FILE) --parents ../terminal/main.cpp ../terminal/mainwindow.cpp ../terminal/settingsdialog.cpp ../terminal/console.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../terminal/mainwindow.ui ../terminal/settingsdialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r terminal.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_terminal.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_terminal.cpp
qrc_terminal.cpp: ../terminal/terminal.qrc \
		../../../../5.10.0/clang_64/bin/rcc \
		../terminal/images/application-exit.png \
		../terminal/images/disconnect.png \
		../terminal/images/clear.png \
		../terminal/images/connect.png \
		../terminal/images/settings.png
	/Users/austin/Qt/5.10.0/clang_64/bin/rcc -name terminal ../terminal/terminal.qrc -o qrc_terminal.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../../5.10.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h ../../../../5.10.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_settingsdialog.cpp moc_console.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_settingsdialog.cpp moc_console.cpp
moc_mainwindow.cpp: ../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../5.10.0/clang_64/lib/QtSerialPort.framework/Headers/QSerialPort \
		../../../../5.10.0/clang_64/lib/QtSerialPort.framework/Headers/qserialport.h \
		../terminal/mainwindow.h \
		moc_predefs.h \
		../../../../5.10.0/clang_64/bin/moc
	/Users/austin/Qt/5.10.0/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/austin/Qt/5.10.0/clang_64/mkspecs/macx-clang -I/Users/austin/Qt/Examples/Qt-5.10.0/serialport/terminal -I/Users/austin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/austin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers -I/Users/austin/Qt/5.10.0/clang_64/lib/QtSerialPort.framework/Headers -I/Users/austin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/austin/Qt/5.10.0/clang_64/lib ../terminal/mainwindow.h -o moc_mainwindow.cpp

moc_settingsdialog.cpp: ../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../../5.10.0/clang_64/lib/QtSerialPort.framework/Headers/QSerialPort \
		../../../../5.10.0/clang_64/lib/QtSerialPort.framework/Headers/qserialport.h \
		../terminal/settingsdialog.h \
		moc_predefs.h \
		../../../../5.10.0/clang_64/bin/moc
	/Users/austin/Qt/5.10.0/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/austin/Qt/5.10.0/clang_64/mkspecs/macx-clang -I/Users/austin/Qt/Examples/Qt-5.10.0/serialport/terminal -I/Users/austin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/austin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers -I/Users/austin/Qt/5.10.0/clang_64/lib/QtSerialPort.framework/Headers -I/Users/austin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/austin/Qt/5.10.0/clang_64/lib ../terminal/settingsdialog.h -o moc_settingsdialog.cpp

moc_console.cpp: ../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/QPlainTextEdit \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../terminal/console.h \
		moc_predefs.h \
		../../../../5.10.0/clang_64/bin/moc
	/Users/austin/Qt/5.10.0/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/austin/Qt/5.10.0/clang_64/mkspecs/macx-clang -I/Users/austin/Qt/Examples/Qt-5.10.0/serialport/terminal -I/Users/austin/Qt/5.10.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/austin/Qt/5.10.0/clang_64/lib/QtGui.framework/Headers -I/Users/austin/Qt/5.10.0/clang_64/lib/QtSerialPort.framework/Headers -I/Users/austin/Qt/5.10.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/austin/Qt/5.10.0/clang_64/lib ../terminal/console.h -o moc_console.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_settingsdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_settingsdialog.h
ui_mainwindow.h: ../terminal/mainwindow.ui \
		../../../../5.10.0/clang_64/bin/uic
	/Users/austin/Qt/5.10.0/clang_64/bin/uic ../terminal/mainwindow.ui -o ui_mainwindow.h

ui_settingsdialog.h: ../terminal/settingsdialog.ui \
		../../../../5.10.0/clang_64/bin/uic
	/Users/austin/Qt/5.10.0/clang_64/bin/uic ../terminal/settingsdialog.ui -o ui_settingsdialog.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../terminal/main.cpp ../terminal/mainwindow.h \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../5.10.0/clang_64/lib/QtSerialPort.framework/Headers/QSerialPort \
		../../../../5.10.0/clang_64/lib/QtSerialPort.framework/Headers/qserialport.h \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../terminal/main.cpp

mainwindow.o: ../terminal/mainwindow.cpp ../../../../5.10.0/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../../5.10.0/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../../5.10.0/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../../5.10.0/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../terminal/mainwindow.h \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../5.10.0/clang_64/lib/QtSerialPort.framework/Headers/QSerialPort \
		../../../../5.10.0/clang_64/lib/QtSerialPort.framework/Headers/qserialport.h \
		ui_mainwindow.h \
		../terminal/console.h \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/QPlainTextEdit \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../terminal/settingsdialog.h \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../terminal/mainwindow.cpp

settingsdialog.o: ../terminal/settingsdialog.cpp ../terminal/settingsdialog.h \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../../5.10.0/clang_64/lib/QtSerialPort.framework/Headers/QSerialPort \
		../../../../5.10.0/clang_64/lib/QtSerialPort.framework/Headers/qserialport.h \
		ui_settingsdialog.h \
		../../../../5.10.0/clang_64/lib/QtGui.framework/Headers/QIntValidator \
		../../../../5.10.0/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../../5.10.0/clang_64/lib/QtSerialPort.framework/Headers/QSerialPortInfo \
		../../../../5.10.0/clang_64/lib/QtSerialPort.framework/Headers/qserialportinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingsdialog.o ../terminal/settingsdialog.cpp

console.o: ../terminal/console.cpp ../terminal/console.h \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/QPlainTextEdit \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/QScrollBar \
		../../../../5.10.0/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o console.o ../terminal/console.cpp

qrc_terminal.o: qrc_terminal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_terminal.o qrc_terminal.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_settingsdialog.o: moc_settingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingsdialog.o moc_settingsdialog.cpp

moc_console.o: moc_console.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_console.o moc_console.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/Users/austin/Qt/Examples/Qt-5.10.0/serialport/terminal || mkdir -p $(INSTALL_ROOT)/Users/austin/Qt/Examples/Qt-5.10.0/serialport/terminal
	$(DEL_FILE) -r $(INSTALL_ROOT)/Users/austin/Qt/Examples/Qt-5.10.0/serialport/terminal/terminal.app
	
	-$(QINSTALL) terminal.app $(INSTALL_ROOT)/Users/austin/Qt/Examples/Qt-5.10.0/serialport/terminal/terminal.app
	-$(STRIP) $(INSTALL_ROOT)/Users/austin/Qt/Examples/Qt-5.10.0/serialport/terminal/terminal.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/austin/Qt/Examples/Qt-5.10.0/serialport/terminal/terminal.app
	-$(DEL_DIR) $(INSTALL_ROOT)/Users/austin/Qt/Examples/Qt-5.10.0/serialport/terminal/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

